CREATE DATABASE GBSDBV1;
-- DROP
CREATE TABLE USERS(
USER_ID INT,
USER_NAME VARCHAR(15) NOT NULL,
USER_PASSWORD VARCHAR(15) NOT NULL,
CREATION_DATE VARCHAR(20) NOT NULL,
NUMBER_OF_ACCOUNTS INT NOT NULL,
ACCOUNT_NUMBER INT NOT NULL,
TOTAL_BALANCE FLOAT NOT NULL,
CONTACT_NUMBER INT NOT NULL,
PRIMARY KEY (USER_ID)
);
